//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizaciones
    {
        public int Id { get; set; }
        public string Cliente { get; set; }
        public string TipoSeguro { get; set; }
        public string FormaPago { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public System.DateTime FechaCotizacion { get; set; }
        public bool Activa { get; set; }
        public string NumeroPoliza { get; set; }
    }
}
